### ISSUE TITLE
About the link to dropbox of DTU dataset

### ISSUE THREAD

**Issue by ChencongZJU** [aejion/NeuFace#1]
Thanks for your great work.
I am trying to evaluate the model on DTU dataset. However, the hyperlink in readme file of [DTU dataset](https://www.dropbox.com/sh/5tam07ai8ch90pf/AADniBT3dmAexvm_J1oL__uoaDTU) seems invalid.

**Comment by aejion** [comment]
Thanks for your attention.
Sorry about our mistake, we have updated the hyperlink of [DTU dataset](https://www.dropbox.com/sh/5tam07ai8ch90pf/AADniBT3dmAexvm_J1oL__uoa).
