### ISSUE TITLE
Train NeuFace on captured multi-view images but do not use ImFace prior

### ISSUE THREAD

**Issue by 07hyx06** [aejion/NeuFace#10]
Hi, thanks for your great work and code!

I try to run NeuFace on a multi-view face image dataset capture by myself. It contains multi-view images of a single identity. 

By reading through the issues, I find that its not very easy to follow the "Train on FaceScape" pipeline. It seems that a lot of processing task should be done, including align the mesh to the ImFace coordinates, crop the face mesh, etc. So I want to follow the "Train on DTU" pipeline. 

My question is that, have you tried to train NeuFace on the same identity from the FaceScape dataset, with and without the ImFace prior (in my understanding "Train on FaceScape" is the one with prior while "Train on DTU" is the one without prior)? If without the ImFace prior, can we obtain plausible relightable face reconstruction results? What about the performance drop compared to the one with prior?

Thanks.

**Comment by aejion** [comment]
Thanks for your attention!
In our experiments, training NeuFace on a face dataset using the "Train on DTU" process can obtain plausible reconstruction results. However, there may be a degradation in performance in terms of appearance and geometry. Additionally, you can also relight the reconstructed results (if your self-captured dataset has the same camera settings, you may try deleting the calibration module for improved relighting results).

**Comment by 07hyx06** [comment]
Got it. Thanks for your quick reply!
