### ISSUE TITLE
Training problem help

### ISSUE THREAD

**Issue by wasahaiah** [aejion/NeuFace#14]
Hi, I met a problem about training. 

I training the processed dataset with 11 images as test set as illustrated in paper. The training results: training PSNR about 14.5 and the evaluated PSNR is about 25.  At the beginning, I doubt the dataset has some problem. But when I evaluate the dataset by your released model(id=1, exp=2), the results are reasonable, i.e. PSNR=31.49 (in the train dataset) and PSRN=30.71(in the test dataset). Can you give me a help?

**Comment by aejion** [comment]
Could you provide more details about your training configuration and results, such as the config file, the number of GPUs, and the rendered images?

**Comment by wasahaiah** [comment]
> Could you provide more details about your training configuration and results, such as the config file, the number of GPUs, and the rendered images?

Thank you for your reply. The config file is almost the same as the file "train_neuface.yaml", except that param 'num_gpus' is set to be 1, because I have only one nvidia 3090D chip. Two images in the tensorboard, are shown below:

![Screenshot 2024-06-20 at 08-06-13 TensorBoard](https://github.com/aejion/NeuFace/assets/26264214/9640d2db-ec8d-4bb6-a801-7d3429a14e56)
![imageData](https://github.com/aejion/NeuFace/assets/26264214/4e13a450-c301-4d62-aeda-3f2de6d12165)

The evaluation results (id=1, exp=2, image:045)are shown below:
![1_045_albedo](https://github.com/aejion/NeuFace/assets/26264214/0923b37e-b4a5-4f8c-b35f-3fca93849251)
![1_045_diffuse](https://github.com/aejion/NeuFace/assets/26264214/068257ec-0485-4375-93ad-8fbb410f7885)
![1_045_fit](https://github.com/aejion/NeuFace/assets/26264214/41f3d853-73bd-4c7f-abb5-0a50db150fde)
![1_045_normal](https://github.com/aejion/NeuFace/assets/26264214/5a489605-cf5c-4405-bc87-46f8992cd080)
![1_045_spec](https://github.com/aejion/NeuFace/assets/26264214/3ef63f71-873b-489a-b357-02cea73353aa)

**Comment by aejion** [comment]
If you are using a single GPU to train NeuFace, it is recommended to increase the num_pixels in the config file. Note that the PSNR shown in TensorBoard is not accurate due to the calibration code. For an accurate PSNR evaluation, please run eval.py. Additionally, as observed in TensorBoard, the render result appears much better than the evaluation. This might be because the wrong ckpt was used when running eval.py.

**Comment by wasahaiah** [comment]
> If you are using a single GPU to train NeuFace, it is recommended to increase the num_pixels in the config file. Note that the PSNR shown in TensorBoard is not accurate due to the calibration code. For an accurate PSNR evaluation, please run eval.py. Additionally, as observed in TensorBoard, the render result appears much better than the evaluation. This might be because the wrong ckpt was used when running eval.py.

Hi, when I used 4 GPU(nvidia 4090) to train NueFace, the PSNR is 25.18, still too lower. I increase the 'num_pixels' to 6000 in the config file, and get PSRN about 26. the result is below:
PSNR:26
![1_044](https://github.com/aejion/NeuFace/assets/26264214/36f24113-889b-447d-9fae-147fd6fba978)
![1_044_albedo](https://github.com/aejion/NeuFace/assets/26264214/6857f20a-d0cb-4627-9ee0-2240f38ba609)
![1_044_diffuse](https://github.com/aejion/NeuFace/assets/26264214/af0b57d7-6c20-4e4d-ba69-81763866d3b7)
![1_0
![1_044_normal](https://github.com/aejion/NeuFace/assets/26264214/c3f70656-8c1d-4562-8f79-da0be83f30bd)
44_fit](https://github.com/aejion/NeuFace/assets/26264214/3c48ccd8-7164-4666-9e22-c55550d991f9)
![1_044_spec](https://github.com/aejion/NeuFace/assets/26264214/aa3fc510-9b04-434e-b091-aebee631f226)

**Comment by aejion** [comment]
Could you please provide the PSNR in detail for each test image?

**Comment by wasahaiah** [comment]
> Could you please provide the PSNR in detail for each test image?

the PSNR of images 47.png, 49.png, 50.png（large rotation）, are small, below 17, others are above 24.  And only image of 52.png , is above 33.

in facescape_multi_dataset.py,  ply_path is the TU model and not the cut mesh?
 I place TU model in the ply_path as suggested.

**Comment by aejion** [comment]
'ply_path' refers to the original TU model, which provides the position of nose.

**Comment by wasahaiah** [comment]
> 'ply_path' refers to the original TU model, which provides the position of nose.

Hi, I have trained a model in 4 V800 GPUs, and get PSNR 33.28 in train set, 26.87 in eval set, with num_pixels: 20000 and sdf_threshold:5e-5.

**Comment by aejion** [comment]
Can you send me your results via email? (zhyzhy@buaa.edu.cn)

**Comment by wasahaiah** [comment]
> ([zhyzhy@buaa.edu.cn](mailto:zhyzhy@buaa.edu.cn))

Have send  it to you. If not received, pls let me know.

**Comment by wasahaiah** [comment]
> Can you send me your results via email? ([zhyzhy@buaa.edu.cn](mailto:zhyzhy@buaa.edu.cn))

Have send  it to you. If not received, pls let me know.
