### ISSUE TITLE
Some missing input files

### ISSUE THREAD

**Issue by kingjg** [aejion/NeuFace#2]
Hi,

It's a fascinating piece of work.

When I tried to run NeuFace on the Facescape dataset, I found some input files were missing. For example, "Rt_scale_dict.json".

How could I get these files or do I need some preprocessing on the dataset?

Thanks.

**Comment by aejion** [comment]
Thanks for your attention!

[Facescape](https://github.com/zhuhao-nju/facescape) provides those input files, you can find the missing files from Facescape dataset.

If you want to run NeuFace on the Facescape dataset, it is recommended to preprocess the images obtained from Facescape by applying a mask to exclude the areas outside the facial region. The mask can be obtained by rendering the provided mesh from the Facescape dataset.

**Comment by kingjg** [comment]
OK, thanks.

Besides, I cannot find the mask jpg files for Facescape and I don't see them in the preprocessed files of Imface. Could you help me know how to get the mask files? Thank you.

**Comment by aejion** [comment]
The mask image can be obtained through the following steps: 1) Using the preprocessing code provided by ImFace to crop the high-quality mesh provided in FaceScape; 2) Rendering the cropped mesh using the camera poses provided by the FaceScape dataset to obtain the final mask.

**Comment by kingjg** [comment]
Thanks for your instruction.

Formerly, I trained 3000 epochs (ID: 1, Expression: 2) without a mask (totally white image), but the rendering performance was really poor. Does the mask of the face play an important role in NeuFace or should I modify some codes to train without a mask? Thank you.

**Comment by aejion** [comment]
Yes, because we utilize ImFace as a facial geometry prior, which only models the facial region. Therefore, masks are required during the training process.

**Comment by kingjg** [comment]
> The mask image can be obtained through the following steps: 1) Using the preprocessing code provided by ImFace to crop the high-quality mesh provided in FaceScape; 2) Rendering the cropped mesh using the camera poses provided by the FaceScape dataset to obtain the final mask.

Thanks for your help!

However, when I try to use the preprocessing codes of IMFace to crop the facial region, the 3D model is cropped from the OBJ file (smooth head model, coordinates range from about -100 to 100). But the camera parameter file provided by Facescape seems to be matched with its PLY 3D models (dense vertices). Could you help me to know how to render the binary mask by the unmatched 3D face model and camera param file? 

Thank you.

**Comment by aejion** [comment]
To match the camera pose, I recommend you refer to this [code](https://github.com/aejion/NeuFace/blob/c6e4ec78f6b0b69b5e9beb9d9aefe58a25459f39/dataset/facescape_multi_dataset.py#LL208C12-L230C35).

**Comment by kingjg** [comment]
Thanks.

Now I get the masks like the following images (please ignore the inverse color, and note that the last image renders from the back view):

<img width="373" alt="image" src="https://github.com/aejion/NeuFace/assets/18000737/f7e803e1-7e2a-4681-96fe-bb6ce4a09b54">
<img width="368" alt="image" src="https://github.com/aejion/NeuFace/assets/18000737/cae56006-d8c0-4ff5-a7da-58d064184dd7">
<img width="369" alt="image" src="https://github.com/aejion/NeuFace/assets/18000737/1af85304-596a-44b1-8977-b65da70e14be">

 However, the performance of the trained model is still not good (PSNR around 10). Is this caused by the masks? Could you help me figure out the problem and reproduce the results in the paper? Thank you!

**Comment by aejion** [comment]
Can you email me the whole train images (include rgb and mask) that you have used?

**Comment by kingjg** [comment]
OK. Thanks!

**Comment by 76donghyun** [comment]
I downloaded the dataset but the Rt_scale_dict.json file was missing. How did you handle this?

**Comment by aejion** [comment]
You can download the missing file at [FaceScape](https://github.com/zhuhao-nju/facescape/tree/master/toolkit/predef) @76donghyun
