### ISSUE TITLE
How to export texture?

### ISSUE THREAD

**Issue by SlimeVRX** [aejion/NeuFace#3]
Thanks for your great work!

My goal: is to import highly detailed meshes and textures into 3D software like Blender, Unreal for rendering

How do export mesh and textures (diffuse, specular, normal)?

![image](https://github.com/aejion/NeuFace/assets/99313947/3c54bddb-7b84-427f-96ed-d65ac3f63421)

Like image

![image](https://github.com/aejion/NeuFace/assets/99313947/453cda44-372a-4c6f-a2ab-ac78438078f3)

**Comment by aejion** [comment]
Thanks for your attention.

We recommend you using [Nerf2Mesh](https://me.kiui.moe/nerf2mesh/) to export detailed meshes and textures. However, integrating neural representations directly into existing rendering tools, such as blender, can be challenging. Moreover, if you want to support downstream rendering tasks like relighting in 3D software, you may need to customize the shader to support neural network.

**Comment by SlimeVRX** [comment]
Thanks for your advice, I will learn about Nerf and Nerf2mesh.
