### ISSUE TITLE
about training data preparation

### ISSUE THREAD

**Issue by flyingshan** [aejion/NeuFace#4]
Hi~
I have some questions on the training data preparation.

According to README, the training data is from the Facescape dataset. Here → https://facescape.nju.edu.cn/Page_Data/ describes the Facescape dataset, and **which part is useful (should be downloaded) for NeuFace**?  And after the data is acquired, **which data preprocess script should I run to proprocess the data properly**?

Looking forward to your reply, thank you!

**Comment by aejion** [comment]
Thanks for your attention.

which part is useful (should be downloaded) for NeuFace: The required data includes multi-view images, reconstructed 3D shapes used for rendering masks(which are included in Multi-view data), and TU Models for adjusting camera poses.

which data preprocess script should I run to preprocess the data properly: Please refer to #2 to preprocess the data.

**Comment by aejion** [comment]
Hi, we have updated the data preprocessing code in our repo. Hope this is helpful! @flyingshan

**Comment by flyingshan** [comment]
Thank you, it will be very useful!
