### ISSUE TITLE
Code converts SH to environment map

### ISSUE THREAD

**Issue by sally-chen** [aejion/NeuFace#8]
Hi, thanks so much for this amazing work!

I'm trying to visualize the environment map from the recovered lighting, and was not sure what is the right convention / coordinate system to use for correct visualization. So I was wondering if you could provide some info on how you converted SH to environment map and environment map to SH? Thanks so much!

**Comment by aejion** [comment]
Thanks for your attention!

We follow [A Neural Rendering Framework for Free-Viewpoint Relighting](https://arxiv.org/abs/1911.11530) to convert environment map to SH and SH to environment map, here is our code (The necessary files can be found in [RNR](https://github.com/LansburyCH/relightable-nr/blob/master/network.py)):

```
import torch
from torch.utils.data import DataLoader

import numpy as np
import cv2
import scipy.io
import dataio
import misc
import render
import sph_harm
import e3nn.o3 as o3

def e3_SH(lmax, directions, sh, rho):
    d = directions[..., [1, 2, 0]]
    basis = torch.zeros((directions.shape[0], (lmax + 1) ** 2)).to(directions.device).float()
    for i in range(lmax + 1):
        basis[..., i ** 2: (i + 1) ** 2] = o3.spherical_harmonics(i, d, normalize=False) * torch.exp(
            - i * (i + 1) / 2 * rho)
    basis = basis.unsqueeze(-1)
    tmp = basis * sh  # (N, 25 or 9, 3)
    return tmp.sum(-2).reshape(1, 100, 200, 3).numpy()  # (N, 3)

# sample light directions on sphere
l_dir_np = scipy.io.loadmat('sphere_samples_4096.mat')['sphere_samples'].transpose() # [3, num_sample]
l_dir = torch.from_numpy(l_dir_np) # [3, num_sample]

# dataset loader for light probes
lp_dataset = dataio.LightProbeDataset(data_dir = 'material_sphere')
print('Start buffering light probe data...')
lp_dataset.buffer_all()
lp_dataloader = DataLoader(lp_dataset, batch_size = 1, shuffle = False, num_workers = 8)

# initialize light samples from light probes
num_lighting = len(lp_dataloader)
lp_idx = 0
lps = []
num_sample = 4096
num_channel = 3
lp_img_w = 3200
lp_img_h = 1600
l_samples = torch.zeros((num_lighting, num_sample, num_channel), dtype = torch.float32)
l_samples_uv = render.spherical_mapping(l_dir)
for lp in lp_dataloader:
    lp_img = lp['lp_img'][0, :].permute((1, 2, 0))
    lps.append(torch.from_numpy(cv2.resize(lp_img.cpu().detach().numpy(), (lp_img_w, lp_img_h), interpolation = cv2.INTER_AREA))) # [H, W, C]
    lp_img = lps[-1]
    l_samples[lp_idx, :] = misc.interpolate_bilinear(lp_img, (l_samples_uv[None, 0, :] * float(lp_img.shape[1])).clamp(max = lp_img.shape[1] - 1), (l_samples_uv[None, 1, :] * float(lp_img.shape[0])).clamp(max = lp_img.shape[0] - 1))[0, :]
    lp_idx += 1
lps = torch.stack(lps)

lmax = 10
print('LightingLP.fit_sh: Computing SH basis value on sampled directions...')
basis_val = torch.from_numpy(sph_harm.evaluate_sh_basis(lmax = lmax, directions = l_dir.cpu().detach().numpy().transpose())).to(l_dir.dtype).to(l_dir.device) # [num_sample, num_basis]
sh_coeff = sph_harm.fit_sh_coeff(samples = l_samples.to(l_dir.device), sh_basis_val = basis_val) # [num_lighting, num_basis, num_channel]
sh_coeff = sh_coeff.numpy()
np.save('sh_coeff.npy', sh_coeff)


# convert sh to env map
lp_recon_h = 100
lp_recon_w = 200
# precompute SH basis value for reconstructing light probe
lp_samples_recon_v, lp_samples_recon_u = torch.meshgrid([torch.arange(start = 0, end = lp_recon_h, step = 1, dtype = torch.float32) / (lp_recon_h - 1),
                                                        torch.arange(start = 0, end = lp_recon_w, step = 1, dtype = torch.float32) / (lp_recon_w - 1)])
lp_samples_recon_uv = torch.stack([lp_samples_recon_u, lp_samples_recon_v]).flatten(start_dim = 1, end_dim = -1)
lp_samples_recon_dir = render.spherical_mapping_inv(lp_samples_recon_uv).permute((1, 0)).cpu().detach().numpy()

ref_recon = e3_SH(lmax, torch.tensor(lp_samples_recon_dir), torch.tensor(sh_coeff[0,:,:]), torch.tensor(0.).float())
ref_recon = torch.relu(torch.tensor(ref_recon)).numpy()

ref_validPix = ref_recon[np.logical_not(np.isnan(ref_recon))]
ref_recon = (ref_recon - ref_validPix.min()) / (ref_validPix.max() - ref_validPix.min())
ref_recon[np.isnan(ref_recon)] = 0
img = cv2.imwrite('env_map.exr', ref_recon[0])
img = cv2.imread('env_map.exr', cv2.IMREAD_ANYCOLOR | cv2.IMREAD_ANYDEPTH)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img = cv2.imwrite('env_map.exr', img)
img.save('env_map.exr')
```

Hope this is helpful!

**Comment by sally-chen** [comment]
Thanks so much for your reply, and this is really helpful! As a follow up question - from your experience would the SH be optimized so that it can actually recover the ground truth lighting? Did you try dataset with ground truth lighting and compare? In my experiment it seems the optimized SH cannot correctly recover the ground truth env map somehow, but maybe I missed something

**Comment by MingwuZheng** [comment]
> Thanks so much for your reply, and this is really helpful! As a follow up question - from your experience would the SH be optimized so that it can actually recover the ground truth lighting? Did you try dataset with ground truth lighting and compare? In my experiment it seems the optimized SH cannot correctly recover the ground truth env map somehow, but maybe I missed something

Thank you for your follow-up question. Based on our experiments with Facescape data, which are predominantly captured under uniform lighting conditions, we've found that Spherical Harmonics (SH) can sometimes recover a portion of the environmental lighting from a Lightstage setup. However, it's important to acknowledge the inherent limitations of SH for this task.

SH typically captures only the low-frequency components of lighting. This makes it inherently challenging to recover high-frequency details or more complex lighting environments accurately.

So, if you're finding that the optimized SH is not recovering the ground truth environmental map in your experiments, it may not necessarily be something you've missed, but rather a limitation of SH itself. For more complex or high-frequency lighting scenarios, it is still a challenging task.

I hope this answers your question. Feel free to ask if you have any more concerns.
