### ISSUE TITLE
How to reconstruct face model with my self multi-images?

### ISSUE THREAD

**Issue by xuduo18311199384** [aejion/NeuFace#9]
I really appreciate your work.
Now i want to reconstruct myself face model with about 100 images, but i do not how to do with it. Can you tell me the process？

**Comment by aejion** [comment]
Thanks.

I refer you to #6.

**Comment by xuduo18311199384** [comment]
Thanks for your reply. As you mentioned "First, I recommend you to register your facial data to the coordinate system of ImFace, then you can use the data preprocess code of ImFace to crop your facial mesh", but i only have rgb images and do not have facial mesh. How i can get facial mesh?

**Comment by aejion** [comment]
You can try using Colmap to get the coarse mesh, and then apply the FaceScape bilinear model to get facial mesh.
